### ISSUE TITLE
회원가입이 되지 않습니다.

### ISSUE THREAD

**Issue by eodmsabc** [swsnu/swpp2019-team7#100]
Must contain at least one number and one lowercase letter, and at least 8 or more characters.

이 비밀번호 경고에 맞춰서 password1 이라는 비밀번호를 사용해 시도했는데
회원가입 진행이 되지 않습니다.

**Comment by jinsun1117** [comment]
Uppercase를 하나 포함해주시기 바랍니다 !! 죄송합니다 바로 바꾸도록 하겠습니다.
