### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by 1207koo** [swsnu/swpp2019-team7#106]
1. qwer1234는 충분히 적합한 비밀번호입니다...ㅠ
2. 0byte 이미지는 무한루프 됩니다. confirm도 안 됩니다.
3. 사이트가 작으면 이미지 넣는 곳이 매우 작아집니다.
4. Add by manually에서 약을 선택하고 텍스트 수정한 뒤에 추가할 수 있습니다

**Comment by jinsun1117** [comment]
1. solved
2. @peterhyun 
3. @lookdeceline 
4. solved
