### ISSUE TITLE
Routing Issues

### ISSUE THREAD

**Issue by jinsun1117** [swsnu/swpp2019-team7#112]
There are two routing issues found
1. When going to undefined address AFTER logging in, it leads to Landing page, with wrong address at 주소창
2. Currently we can go to addcustompill without uploading image by 주소창. This is bad, because then we won't be able to send it the image id

**Comment by jinsun1117** [comment]
이건 아마 404 페이지를 따로 만들어야 할거같은데 어떻게들 생각하시나요
@peterhyun  @lookdeceline  @sharkmir1

**Comment by sharkmir1** [comment]
음 맞긴 한데 시간 문제가...
