### ISSUE TITLE
Store image pill as unauthorized user

### ISSUE THREAD

**Issue by jinsun1117** [swsnu/swpp2019-team7#36]
If, 
user takes picture at Landing page, 
-> Login to store picture
-> Login
-> Dashboard

or even worse,
->Signup
->Dashboard

How are we to store the tempimage and image to backend storage?

**Comment by sharkmir1** [comment]
Already Implemented Image Saving Routine for Unauthorized User.
All we need to now for image API is to add on authentication process in our image process.
