### ISSUE TITLE
Connect Firebase Cloud Messaging with Pillbox frontend

### ISSUE THREAD

**Issue by sharkmir1** [swsnu/swpp2019-team7#48]
We will first try out connecting FCM and Pillbox frontend, minimizing backend logic. After this, we will customize our notification to be handled from our Django models.

**Comment by sharkmir1** [comment]
Even if we minimize interaction with our App backend, we still need to modify our User model to handle Firebase Notification Instance ID.

**Comment by sharkmir1** [comment]
Refer to [this](https://stackoverflow.com/questions/38769388/what-do-i-use-as-the-user-token-to-subscribe-users-to-topics-in-firebase)

**Comment by peterhyun** [comment]
If we happen to use cronjobs
https://www.ostechnix.com/a-beginners-guide-to-cron-jobs/
https://pypi.org/project/django-cronjobs/
https://stackoverflow.com/questions/573618/django-set-up-a-scheduled-job

**Comment by peterhyun** [comment]
https://github.com/xtrinch/fcm-django

-> README.md is very useful
