### ISSUE TITLE
switch to MySql

### ISSUE THREAD

**Issue by lookdeceline** [swsnu/swpp2019-team7#51]
sql lite ==> my sql

don't forget about it!

**Comment by sharkmir1** [comment]
Successfully migrated to MySQL. Here is tutorial:    

### Mac OS
1. Install MySql by
`homebrew install mysql`

2. Install mysqlclient by 
`pip install mysqlclient`

3. Start mysql service by
`brew services start mysql`
(to stop homebrew mysql service, you can `brew services stop mysql`)

4. Login to mysql by
`mysql -u root`

5. Create Database in mysql by
`CREATE DATABASE pillbox;`    
`CREATE USER jay IDENTIFIED BY 'pillbox1!'; ` <- should exactly be jay / pillbox1!    
`GRANT ALL PRIVILEGES ON pillbox.* TO jay;`    
`FLUSH PRIVILEGES'    
'exit'    

6. Now our mysql is all set. Now, we should migrate Django DB to MySQL.
Type `python manage.py makemigrations appname` for each app <- This should be done before any migrations!!!
Type `python manage.py migrate`    
Type `python manage.py runserver` to check if it runs well.

### Linux (Ubuntu)
1. Ubuntu는 `brew install mysql` 대신 `sudo apt-get install mysql-server` 등등으로 대체하면 됨 ^^

**Comment by jinsun1117** [comment]
Need to consistantly refer

**Comment by jinsun1117** [comment]
Linux needs to do additional `sudo apt-get install libmysqlclient-dev` between 1 and 2

**Comment by jinsun1117** [comment]
For linux, No.3 is `sudo systemctl start mysql`

**Comment by peterhyun** [comment]
<In case of encoding error>
use {databaseName}
alter table {table name} convert to character set utf8mb4;
