### ISSUE TITLE
[Mid Presentation] 건강기능식품만 하는것에 대한 코멘트들

### ISSUE THREAD

**Issue by jinsun1117** [swsnu/swpp2019-team7#57]
- 건강기능식품은 굳이 주기적/일정하게 먹을 필요가 있나 싶다 
- 피임약같은 처방약이 규칙적으로 먹어야 하지 않나 싶다 
- 약 먹는 안내 같은건 이미 AI 스피커 연동해서 많이 하지 않는지 
- 타겟을 나이많고 병원가는 사람보다는 몸관리 철저하게 하려는 사람에게 맞추는것도

**Comment by peterhyun** [comment]
I will close this unless we want to add more data other than 건강기능식품s
