### ISSUE TITLE
[Mid Presentation] Notification related

### ISSUE THREAD

**Issue by jinsun1117** [swsnu/swpp2019-team7#58]
-크롬이 실제로 약먹는걸 알려주는 노티로 적합한지 의문 -> 카톡 잘 해봅시다
-노티 무시할떄를 대비 유저 반응 이끌어낼 방법은?
-노티와 함께 '약을 먹었습니다'라는 체크도 같이 하는것도 좋을듯하다

**Comment by peterhyun** [comment]
크롬 노티로 소리 기능까지 추가하겠습니다

**Comment by lookdeceline** [comment]
@peterhyun 
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 노티마스터

**Comment by peterhyun** [comment]
Chrome sound noti is IMPOSSIBLE. Proven. Too bad : (
