### ISSUE TITLE
telegram bot integration

### ISSUE THREAD

**Issue by sharkmir1** [swsnu/swpp2019-team7#67]
Currently implemented webhook for telegram bot, such that when bot receives some message, the telegram server sends us post request to notify us.

**Comment by sharkmir1** [comment]
But to run the webhook, we need public ip address to which telegram server will send request. Since we do not have any domain yet, in order to run webhook in local, you should download [ngrok](https://ngrok.com/) and start it at the same port with the backend (8000 default) like
`ngrok http 8000`.
This will give you temporary public address for our backend. Then, we need to register this as our webhook, by sending GET request to "api.telegram.org/bot1007785006:AAGZNrBr4w-Eovrf-ZQj7P7MSN6KS3Cl23g/setWebHook?url=https://SOMETHING.ngrok.io".

But I recommend not to try this at home... except when you really need it for debugging!

**Comment by jinsun1117** [comment]
Open again for Reference
