### ISSUE TITLE
Notification Setting API modification

### ISSUE THREAD

**Issue by sharkmir1** [swsnu/swpp2019-team7#77]
In order to support users to set notification interval,
we need to initialize each user's notification interval setting when user enables 'notification_interval'. 
So modify the `notiSetting` function in `notiSetting/views.py` such that when user enables noti setting and there's no previous notification interval setting associated with this user, new rows of class NotificationInterval are added for this user.

I have implemented helper function `initialize_user_interval` for this in NotificationInterval Class, in branch `notification-backend`.

**Comment by jinsun1117** [comment]
Solved
