### ISSUE TITLE
[frontend] 약 등록 오류

### ISSUE THREAD

**Issue by jinsun1117** [swsnu/swpp2019-team7#88]
분명히 backend api로는 홍삼정을 사진찍어 올렸고, DemoWidget의 결과에도 홍삼정으로 이름이 찍하는데 프론트에는 활력삼 캡슐이 찍힘..?

**Comment by lookdeceline** [comment]
reproduce좀 부탁합니당 ㅠ
아 그리고 어디 demo widget? 로그인 된 상태에서 말이지?
@jinsun1117

**Comment by jinsun1117** [comment]
Solved. make sure MySQL is version 8, not 5.
