### ISSUE TITLE
같은 약을 두번 올렸을 때/약이 아닌 아무 사진이나 올렸을 때

### ISSUE THREAD

**Issue by peterhyun** [swsnu/swpp2019-team7#89]
alert 메시지 등의 front단에서 변화가 필요. 지금은 그냥 console에서 에러 확인 가능

**Comment by jinsun1117** [comment]
* 같은 약 두번
* 약이 아닌 아무 사진
* 사진이 아닌 파일

이외에도 
로그인시
* 아이디/혹은 비번 오류(메시지 다듬기)
* 서버가 respond를 안하는 것이나 서버에서 에러가 터진것도 현재는 아이디/비번 에러로 뜸
