### ISSUE TITLE
랩 세션 버그 리포트는 이곳에 부탁드립니다!!!

### ISSUE THREAD

**Issue by peterhyun** [swsnu/swpp2019-team7#97]
![41c7c72026a2d2e64c18a921ec7190ce](https://user-images.githubusercontent.com/22678965/70227402-ddfaf980-1795-11ea-96b9-77c55aaea794.jpg)

**Comment by kanghc0217** [comment]
![image](https://user-images.githubusercontent.com/40143716/70228114-26ff7d80-1797-11ea-97f9-3c8a6b1c2365.png)

악! 비타500 찾아주세요!
(비타500은 약이 아닌가요..?)

**Comment by haesookim** [comment]
landing page에서 약 사진이 없어서 아무 사진을 넣었는데, Error during upload가 뜨는 게 그것 때문인가요?

**Comment by iamsungyeonjoo** [comment]
![image](https://user-images.githubusercontent.com/33143827/70228151-38488a00-1797-11ea-8d18-e0c65b401e7d.png)
유산균 락토핏은 인식하지 못하는 건가여?
왜 안되는지 이유를 알려주세요!

**Comment by haesookim** [comment]
sign up이 안 됩니다! 계속 password regex에서 걸리고 있어요

**Comment by HaeTheong** [comment]
저도 궁금해서 타이레놀 사진으로 해봤는데 안됩니다. 회원가입이 안돼서 로그인을 해야 오류가 안나는 건지 확인이 안되네요.

**Comment by ttoru96** [comment]
sign up이 안됩니다 password 인증 과정에서 걸립니다
제가 쓴 password는 1iluvyolo 입니다

환경: macOS Sierra
브라우저: chrome

**Comment by haesookim** [comment]
<img width="1440" alt="Screen Shot 2019-12-05 at 7 43 56 PM" src="https://user-images.githubusercontent.com/13305988/70228378-99705d80-1797-11ea-8246-994917e281b9.png">

버그는 아니지만 이 부분에서 hover시 색이 바뀐다거나, 제가 뭘 보고 있는 지 알려주면 좋겠습니다. (뭘 클릭하게 되는지 마진이 없어서 불확실하기도 하고요ㅠㅠ)

**Comment by iamsungyeonjoo** [comment]
![image](https://user-images.githubusercontent.com/33143827/70228502-cae92900-1797-11ea-88c0-a08cbebd9f0e.png)
이부분은 클릭해도 아무런 변화가 없습니다.

**Comment by peterhyun** [comment]
> ![image](https://user-images.githubusercontent.com/33143827/70228151-38488a00-1797-11ea-8d18-e0c65b401e7d.png)
> 유산균 락토핏은 인식하지 못하는 건가여?
> 왜 안되는지 이유를 알려주세요!

아마 디비에 없는 것 같습니다.ㅜㅜ 이런 경우에 대비해서 유저가 Custom Pill을 추가할 수 있도록 개발 예정에 있습니다. 감사합니다!

**Comment by peterhyun** [comment]
> ![image](https://user-images.githubusercontent.com/33143827/70228502-cae92900-1797-11ea-88c0-a08cbebd9f0e.png)
> 이부분은 클릭해도 아무런 변화가 없습니다.

아직 개발하지 않은 부분입니다! 의견 감사합니다.

**Comment by iamsungyeonjoo** [comment]
![image](https://user-images.githubusercontent.com/33143827/70228602-f79d4080-1797-11ea-9756-8865dff9497a.png)
이미 존재하는 상품 군 중에서 manually 검색해서 추가했는데
사진도 같이 볼 수 있으면 좋겠습니다. 제가 생각한 것과 같은 제품인 지 알기 어려울 것 같습니다.

**Comment by HaeTheong** [comment]
로그인 후 랜딩페이지로 돌아가보니 로그아웃이 되는 것 같아요

**Comment by iamsungyeonjoo** [comment]
알림은 어디서 어떻게 받는건가요?

**Comment by peterhyun** [comment]
> 알림은 어디서 어떻게 받는건가요?

나중에 설명을 추가하는 UI를 추가하도록 하겠습니다. 감사합니다.

**Comment by ttoru96** [comment]
제가 7:50pm에 알림이 오도록 설정을 해봤는데(설정을 한 건 7:48pm에 했습니다), 알림이 오지 않았습니다 

환경: macOS Sierra | chrome

<img width="1059" alt="Screen Shot 2019-12-05 at 7 50 44 PM" src="https://user-images.githubusercontent.com/44546247/70228979-accff880-1798-11ea-9022-aaad06de947b.png">

**Comment by peterhyun** [comment]
> landing page에서 약 사진이 없어서 아무 사진을 넣었는데, Error during upload가 뜨는 게 그것 때문인가요?

안녕하세요, 혹시 어떤 사진인지 올려 주실 수 있으신가요? 어떤 확장자는 작동이 안되기 때문에 에러가 떴을 가능성이 있습니다.

**Comment by haesookim** [comment]
> > landing page에서 약 사진이 없어서 아무 사진을 넣었는데, Error during upload가 뜨는 게 그것 때문인가요?
> 
> 안녕하세요, 혹시 어떤 사진인지 올려 주실 수 있으신가요? 어떤 확장자는 작동이 안되기 때문에 에러가 떴을 가능성이 있습니다.

음 정확히 어떤 사진이었는지는 기억이 나지 않으나 확장자는 확실히 png였습니다 (맥에서 화면 캡쳐한 사진을 넣었었습니다)
